#!/usr/bin/env python3
"""Tests for bin/render_roadmap.py -- WORKLOG-SPEC section 13.1.

The renderer must be byte-deterministic: the pre-commit freshness check
regenerates and diffs, so any nondeterminism (wall-clock timestamps, dict
order) makes every commit fail.
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "bin"))
sys.path.insert(0, os.path.dirname(__file__))
from render_roadmap import render  # noqa: E402
from test_fold import write_log  # noqa: E402


def ev(n, item, op, **kw):
    e = {"ev": f"01J8X{n:04d}A0", "ts": "t", "actor": "t", "item": item, "op": op}
    e.update(kw)
    return e


class TestDeterminism(unittest.TestCase):
    EVENTS = [
        ev(1, "E1", "create", set={"type": "epic", "title": "Auth refactor",
                                   "status": "todo", "priority": "P0"}),
        ev(2, "T1", "create", set={"type": "task", "title": "Extract middleware",
                                   "status": "in_progress", "priority": "P0",
                                   "parent": "E1"}),
        ev(3, "T2", "create", set={"type": "task", "title": "Session migration",
                                   "status": "todo", "priority": "P1",
                                   "parent": "E1", "depends_on": ["T1"]}),
        # Taxonomy variety: kind mix, milestones, and a kindless create (triage)
        # must all render byte-identically regardless of file order.
        ev(4, "B1", "create", set={"level": "task", "kind": "bug",
                                   "title": "Fix login", "status": "todo",
                                   "priority": "P1", "parent": "E1",
                                   "milestone": "v0.7.0"}),
        ev(5, "U1", "create", set={"title": "Untagged idea",
                                   "status": "todo", "priority": "P2"}),
        ev(6, "O1", "create", set={"level": "task", "kind": "ops",
                                   "title": "Rotate keys", "status": "todo",
                                   "priority": "P2", "milestone": "v0.8.0"}),
    ]

    def test_identical_output_regardless_of_file_order(self):
        a = render([write_log(self.EVENTS)])
        b = render([write_log(list(reversed(self.EVENTS)))])
        self.assertEqual(a, b)

    def test_two_renders_of_same_log_are_identical(self):
        path = write_log(self.EVENTS)
        self.assertEqual(render([path]), render([path]))

    def test_generated_marker_and_hash_present(self):
        out = render([write_log(self.EVENTS)])
        self.assertIn("<!-- GENERATED by worklog roadmap-render. DO NOT EDIT. -->", out)
        self.assertTrue(out.startswith("---\nwiki_key: roadmap\n"), out[:80])
        self.assertIn("doc_type: roadmap", out)
        self.assertIn("truth_state: current", out)
        self.assertIn("source_hash: ", out)
        self.assertIn("generated_at: ", out)
        self.assertNotIn("generated_at: never", out)


class TestSections(unittest.TestCase):
    def test_in_progress_lands_in_now(self):
        out = render([write_log([
            ev(1, "A", "create", set={"type": "task", "title": "Mid-flight",
                                      "status": "in_progress", "priority": "P2"}),
        ])])
        now = out.split("## Now")[1].split("## Next")[0]
        self.assertIn("Mid-flight", now)

    def test_unblocked_p2_is_next_blocked_p2_is_later(self):
        out = render([write_log([
            ev(1, "D1", "create", set={"type": "task", "title": "Dep",
                                       "status": "todo", "priority": "P2"}),
            ev(2, "B1", "create", set={"type": "task", "title": "Waiting",
                                       "status": "todo", "priority": "P2",
                                       "depends_on": ["D1"]}),
        ])])
        nxt = out.split("## Next")[1].split("## Later")[0]
        later = out.split("## Later")[1]
        self.assertIn("Dep", nxt)
        self.assertIn("Waiting", later)

    def test_blocked_by_column_names_the_open_blocker(self):
        out = render([write_log([
            ev(1, "DEP12345XX", "create", set={"type": "task", "title": "Dep",
                                               "status": "todo", "priority": "P2"}),
            ev(2, "B1", "create", set={"type": "task", "title": "Waiting",
                                       "status": "todo", "priority": "P2",
                                       "depends_on": ["DEP12345XX"]}),
        ])])
        self.assertIn("DEP12345", out.split("## Later")[1])

    def test_closed_items_and_epics_do_not_appear_as_rows(self):
        out = render([write_log([
            ev(1, "E1", "create", set={"type": "epic", "title": "TheEpic",
                                       "status": "todo", "priority": "P1"}),
            ev(2, "T1", "create", set={"type": "task", "title": "Shipped",
                                       "status": "todo", "priority": "P1",
                                       "parent": "E1"}),
            ev(3, "T1", "close", set={"status": "done"}),
            ev(4, "T2", "create", set={"type": "task", "title": "Open task",
                                       "status": "todo", "priority": "P1",
                                       "parent": "E1"}),
        ])])
        self.assertNotIn("| Shipped |", out)          # closed: no table row
        self.assertNotIn("| TheEpic |", out)          # epic: heading, not row
        self.assertIn("### TheEpic", out)


class TestEpicProgress(unittest.TestCase):
    def test_done_counts_cancelled_does_not(self):
        out = render([write_log([
            ev(1, "E1", "create", set={"type": "epic", "title": "Auth",
                                       "status": "todo", "priority": "P1"}),
            ev(2, "T1", "create", set={"type": "task", "title": "One",
                                       "status": "todo", "priority": "P1", "parent": "E1"}),
            ev(3, "T2", "create", set={"type": "task", "title": "Two",
                                       "status": "todo", "priority": "P1", "parent": "E1"}),
            ev(4, "T3", "create", set={"type": "task", "title": "Three",
                                       "status": "todo", "priority": "P1", "parent": "E1"}),
            ev(5, "T2", "close", set={"status": "done"}),
            ev(6, "T3", "close", set={"status": "cancelled"}),
        ])])
        self.assertIn("1 of 2 done", out)


class TestNeedsAttention(unittest.TestCase):
    def test_conflict_is_surfaced_with_resolve_hint(self):
        out = render([write_log([
            ev(1, "A1", "create", set={"type": "task", "title": "Contested",
                                       "status": "todo", "priority": "P1"}),
            ev(2, "A1", "conflict", set={"field": "priority",
                                         "local": "P1", "remote": "P0"}),
        ])])
        self.assertIn("## Needs attention", out)
        self.assertIn("worklog resolve A1 --field priority", out)


class TestNeedsClassification(unittest.TestCase):
    def test_triage_item_listed_and_counted(self):
        out = render([write_log([
            ev(1, "T1", "create", set={"level": "task", "kind": "triage",
                                       "title": "Sort me", "status": "todo",
                                       "priority": "P2"}),
        ])])
        self.assertIn("## Needs classification", out)
        self.assertIn("- T1 Sort me (task)", out)
        self.assertIn("1 unclassified._", out)

    def test_kindless_create_folds_to_triage_and_lands_here(self):
        # Spec section 2.3: no kind on create => triage, never a silent feature.
        out = render([write_log([
            ev(1, "T1", "create", set={"title": "Mystery", "status": "todo",
                                       "priority": "P2"}),
        ])])
        self.assertIn("## Needs classification", out)
        self.assertIn("- T1 Mystery (task)", out)
        self.assertIn("1 unclassified._", out)

    def test_section_omitted_when_all_classified(self):
        out = render([write_log([
            ev(1, "T1", "create", set={"level": "task", "kind": "feature",
                                       "title": "Classified", "status": "todo",
                                       "priority": "P2"}),
        ])])
        self.assertNotIn("## Needs classification", out)
        self.assertIn("0 unclassified._", out)  # always shown; zero is good news


class TestKindMix(unittest.TestCase):
    def test_mixed_kind_epic_shows_mix_segment(self):
        out = render([write_log([
            ev(1, "E1", "create", set={"level": "epic", "kind": "feature",
                                       "title": "Mixed", "status": "todo",
                                       "priority": "P1"}),
            ev(2, "T1", "create", set={"level": "task", "kind": "feature",
                                       "title": "F", "status": "todo",
                                       "priority": "P1", "parent": "E1"}),
            ev(3, "T2", "create", set={"level": "task", "kind": "bug",
                                       "title": "B", "status": "todo",
                                       "priority": "P1", "parent": "E1"}),
            ev(4, "T3", "create", set={"level": "task", "kind": "ops",
                                       "title": "O", "status": "done",
                                       "priority": "P1", "parent": "E1"}),
        ])])
        # counts the whole subtree, open+closed; zero-count kinds omitted
        self.assertIn("### Mixed  ·  P1  ·  1 of 3 done  ·  feature 1 / bug 1 / ops 1", out)

    def test_all_feature_epic_shows_no_mix_segment(self):
        out = render([write_log([
            ev(1, "E1", "create", set={"level": "epic", "kind": "feature",
                                       "title": "Plain", "status": "todo",
                                       "priority": "P1"}),
            ev(2, "T1", "create", set={"level": "task", "kind": "feature",
                                       "title": "F1", "status": "todo",
                                       "priority": "P1", "parent": "E1"}),
            ev(3, "T2", "create", set={"level": "task", "kind": "feature",
                                       "title": "F2", "status": "todo",
                                       "priority": "P1", "parent": "E1"}),
        ])])
        self.assertIn("### Plain  ·  P1  ·  0 of 2 done", out)
        self.assertNotIn("feature 2", out)


class TestMilestones(unittest.TestCase):
    def test_grouping_and_unanimous_derived_epic_milestone(self):
        out = render([write_log([
            ev(1, "E1", "create", set={"level": "epic", "kind": "feature",
                                       "title": "Uni", "status": "todo",
                                       "priority": "P1"}),
            ev(2, "T1", "create", set={"level": "task", "kind": "feature",
                                       "title": "A", "status": "todo",
                                       "priority": "P1", "parent": "E1",
                                       "milestone": "v0.7.0"}),
            ev(3, "T2", "create", set={"level": "task", "kind": "feature",
                                       "title": "B", "status": "todo",
                                       "priority": "P1", "parent": "E1",
                                       "milestone": "v0.7.0"}),
        ])])
        self.assertIn("## Milestones", out)
        milestones = out.split("## Milestones")[1]
        self.assertIn("### v0.7.0", milestones)
        self.assertIn("| T1 | A |", milestones)
        self.assertIn("| T2 | B |", milestones)
        self.assertIn("### Uni  ·  P1  ·  0 of 2 done  ·  → v0.7.0", out)

    def test_mixed_child_milestones_show_mixed_and_sorted_headings(self):
        out = render([write_log([
            ev(1, "E1", "create", set={"level": "epic", "kind": "feature",
                                       "title": "Split", "status": "todo",
                                       "priority": "P1"}),
            ev(2, "T1", "create", set={"level": "task", "kind": "feature",
                                       "title": "A", "status": "todo",
                                       "priority": "P1", "parent": "E1",
                                       "milestone": "v0.8.0"}),
            ev(3, "T2", "create", set={"level": "task", "kind": "feature",
                                       "title": "B", "status": "todo",
                                       "priority": "P1", "parent": "E1",
                                       "milestone": "v0.7.0"}),
        ])])
        self.assertIn("·  → mixed", out)
        milestones = out.split("## Milestones")[1]
        self.assertLess(milestones.index("### v0.7.0"), milestones.index("### v0.8.0"))

    def test_section_omitted_when_nothing_carries_a_milestone(self):
        out = render([write_log([
            ev(1, "T1", "create", set={"level": "task", "kind": "feature",
                                       "title": "Loose", "status": "todo",
                                       "priority": "P2"}),
        ])])
        self.assertNotIn("## Milestones", out)


class TestEmptyLog(unittest.TestCase):
    def test_empty_log_renders_all_empty_states(self):
        out = render([write_log([])])
        self.assertIn("0 epic(s) in flight, 0 open item(s), 0 blocked, "
                      "0 unclassified._", out)
        self.assertIn("_Nothing here._", out)
        self.assertNotIn("## Needs classification", out)
        self.assertNotIn("## Milestones", out)
        self.assertIn("generated_at: never", out)


if __name__ == "__main__":
    unittest.main()
