#!/usr/bin/env python3
"""Tests for the IA & content model foundation: wiki_key derivation,
frontmatter parsing, truth_state assignment, the content inventory, and
the `worklog wiki-key` / `worklog ia-inventory` commands."""
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "bin"))
import ia


def run(cwd, *args):
    return subprocess.run([sys.executable, os.path.join(cwd, "bin", "worklog"), *args],
                          cwd=cwd, capture_output=True, text=True)


class TestSchemaSync(unittest.TestCase):
    """schema/doc.schema.json + schema/entity.schema.json and bin/ia.py are
    deliberate duplicates (dependency-free bin/); this pins them equivalent
    so they cannot silently diverge before the Phase 5 hard-fail promotion."""

    def test_doc_schema_json_matches_ia_constants(self):
        with open(os.path.join(ROOT, "schema", "doc.schema.json")) as fh:
            schema = json.load(fh)
        props = schema["properties"]
        self.assertEqual(schema["required"], list(ia.REQUIRED_ALL))
        self.assertEqual(props["doc_type"]["enum"], list(ia.DOC_TYPES))
        self.assertEqual(props["truth_state"]["enum"], list(ia.TRUTH_STATES))
        self.assertEqual(
            props["relates_to"]["items"]["properties"]["type"]["enum"],
            list(ia.EDGE_TYPES))
        self.assertEqual(schema["x-required-by-type"],
                         {k: list(v) for k, v in ia.REQUIRED_BY_TYPE.items()})

    def test_entity_schema_json_matches_ia_constants(self):
        with open(os.path.join(ROOT, "schema", "entity.schema.json")) as fh:
            schema = json.load(fh)
        props = schema["properties"]
        self.assertEqual(schema["required"], list(ia.REQUIRED_ALL))
        self.assertEqual(props["doc_type"]["enum"], list(ia.ENTITY_TYPES))
        self.assertEqual(props["truth_state"]["enum"], list(ia.TRUTH_STATES))
        self.assertEqual(
            props["relates_to"]["items"]["properties"]["type"]["enum"],
            list(ia.EDGE_TYPES))
        self.assertEqual(schema["x-required-by-type"],
                         {k: list(v) for k, v in ia.REQUIRED_BY_ENTITY.items()})

    def test_doc_and_entity_types_are_disjoint(self):
        self.assertEqual(set(ia.DOC_TYPES) & set(ia.ENTITY_TYPES), set())


class TestParsing(unittest.TestCase):
    def test_front_matter_lists_maps_and_block_lists(self):
        meta, body = ia.parse_front_matter(
            "---\n"
            "slug: x\n"
            "items: [01A, 01B]\n"
            "window: {from: 2026-07-18T20:56:42Z, to: 2026-07-19T20:57:01Z}\n"
            "supersedes: null\n"
            "id: 3\n"
            "relates_to:\n"
            "  - {type: decides, target: adr/0001-x}\n"
            "---\nbody\n")
        self.assertEqual(meta["items"], ["01A", "01B"])
        self.assertEqual(meta["window"]["from"], "2026-07-18T20:56:42Z")
        self.assertIsNone(meta["supersedes"])
        self.assertEqual(meta["id"], 3)
        self.assertEqual(meta["relates_to"],
                         [{"type": "decides", "target": "adr/0001-x"}])
        self.assertEqual(body.strip(), "body")

    def test_no_fence_returns_full_text(self):
        meta, body = ia.parse_front_matter("# Just a doc\n")
        self.assertEqual(meta, {})
        self.assertEqual(body, "# Just a doc\n")

    def test_dump_round_trips_through_parse(self):
        meta = {"wiki_key": "plan/x", "aliases": ["a", "b"], "id": 7,
                "supersedes": None,
                "relates_to": [{"type": "references", "target": "spec"}]}
        text = "---\n" + ia.dump_simple_yaml(meta) + "---\n"
        back, _ = ia.parse_front_matter(text)
        self.assertEqual(back, meta)

    def test_html_comment_meta(self):
        meta = ia.html_comment_meta(
            "<!-- GENERATED by worklog roadmap-render. DO NOT EDIT. -->\n"
            "<!-- source-hash: 2e9ff8ee -->\n"
            "<!-- generated-at: 2026-07-22T19:01:38Z -->\n")
        self.assertEqual(meta["generated_at"], "2026-07-22T19:01:38Z")
        self.assertEqual(meta["source_hash"], "2e9ff8ee")


class TestKeys(unittest.TestCase):
    def test_derivation_rules(self):
        cases = {
            "docs/plans/2026-07-22-ia-content-model.md": "plan/2026-07-22-ia-content-model",
            "docs/roadmap.md": "roadmap",
            "docs/roadmap/2026-07-21_v0.12.1-release.md": "roadmap-snapshot/2026-07-21_v0.12.1-release",
            "docs/status/2026-07-19-daily.md": "status/2026-07-19-daily",
            "docs/designs/current_design_doc.md": "design/current-design-doc",
            "docs/designs/2026-07-21_v0.12.1-release_design_doc.md":
                "design/2026-07-21_v0.12.1-release-design-doc",
            "docs/adr/0001-event-log-fold-union-merge.md": "adr/0001-event-log-fold-union-merge",
            "docs/user_guide/cli-reference.md": "guide/cli-reference",
            "docs/wiki-home.md": "home",
            "docs/worklog-spec.md": "spec",
        }
        for path, want in cases.items():
            self.assertEqual(ia.derive_canonical_key(path), want, path)
        self.assertIsNone(ia.derive_canonical_key("docs/migrations/0001-type-split.md"))
        # folder READMEs are navigation, not typed docs (generic repos have them)
        for p in ("docs/plans/README.md", "docs/status/README.md",
                  "docs/adr/README.md", "docs/user_guide/README.md"):
            self.assertIsNone(ia.classify(p), p)
        self.assertIsNone(ia.classify("README.md"))

    def test_legacy_key_seeded_from_ledger(self):
        ledger = {"plan/old": {"source": "docs/plans/2026-07-01-old.md"}}
        key, canonical, aliases = ia.resolve_key("docs/plans/2026-07-01-old.md", ledger)
        self.assertEqual(key, "plan/old")                    # verbatim: links win
        self.assertEqual(canonical, "plan/2026-07-01-old")
        self.assertEqual(aliases, ["plan/old"])

    def test_new_doc_gets_canonical_key(self):
        key, canonical, aliases = ia.resolve_key("docs/plans/2026-08-01-new.md", {})
        self.assertEqual(key, "plan/2026-08-01-new")
        self.assertEqual(aliases, [])


class TestInventory(unittest.TestCase):
    """Sandbox repo with one doc of each flavor."""

    def setUp(self):
        self.dir = tempfile.mkdtemp(prefix="worklog-ia-")
        self.addCleanup(shutil.rmtree, self.dir, ignore_errors=True)
        shutil.copytree(os.path.join(ROOT, "bin"), os.path.join(self.dir, "bin"))
        shutil.copytree(os.path.join(ROOT, "schema"), os.path.join(self.dir, "schema"))
        for d in ("docs/plans", "docs/status", "docs/adr", "docs/user_guide", ".work"):
            os.makedirs(os.path.join(self.dir, d))
        self.write("docs/plans/2026-07-01-alpha.md",
                   "---\ndate: 2026-07-01\nslug: alpha\ntitle: Alpha\n"
                   "epic: null\nitems: [01AAAA]\n---\n# Alpha\n")
        self.write("docs/plans/2026-07-02-beta.md",
                   "---\ndate: 2026-07-02\nslug: beta\n"
                   "title: Beta (supersedes alpha)\nepic: null\nitems: []\n---\n# Beta\n")
        self.write("docs/status/2026-07-01-daily.md",
                   "---\nkind: daily\ndate: 2026-07-01\nwindow: {from: a, to: b}\n"
                   "through: 01AAAA\ngenerated_at: 2026-07-01T00:00:00Z\n---\n# S1\n")
        self.write("docs/status/2026-07-02-daily.md",
                   "---\nkind: daily\ndate: 2026-07-02\nwindow: {from: b, to: c}\n"
                   "through: 01AAAA\ngenerated_at: 2026-07-02T00:00:00Z\n---\n# S2\n")
        self.write("docs/adr/0001-x.md",
                   "---\nid: 1\nslug: x\ntitle: X\ndate: 2026-07-01\n"
                   "status: accepted\n---\n# ADR-0001\n\n## Context\nc\n\n"
                   "## Decision\nd\n\n## Consequences\nq\n")
        self.write("docs/user_guide/user-guide.md", "# User guide\n")
        self.write(".work/published.json", json.dumps(
            {"plan/alpha": {"source": "docs/plans/2026-07-01-alpha.md",
                            "url": "https://x/wiki/Plan-alpha"},
             "user-guide": {"source": "docs/user_guide/user-guide.md"}}))

    def write(self, rel, text):
        with open(os.path.join(self.dir, rel), "w", encoding="utf-8") as fh:
            fh.write(text)

    def records(self):
        cwd = os.getcwd()
        os.chdir(self.dir)
        try:
            return ia.build_records()
        finally:
            os.chdir(cwd)

    def test_inventory_records_and_truth(self):
        recs = self.records()
        alpha = recs["plan/alpha"]                     # legacy ledger key
        self.assertEqual(alpha["canonical_key"], "plan/2026-07-01-alpha")
        self.assertEqual(alpha["aliases"], ["plan/alpha"])
        self.assertEqual(alpha["wiki"], "https://x/wiki/Plan-alpha")
        # beta's title says "supersedes alpha" -> derived reverse edge
        self.assertEqual(alpha["truth_state"], "superseded")
        self.assertEqual(alpha["superseded_by"], "plan/2026-07-02-beta")
        # unpublished doc gets the canonical key
        self.assertIn("plan/2026-07-02-beta", recs)
        # newest daily is current, older archived
        self.assertEqual(recs["status/2026-07-02-daily"]["truth_state"], "current")
        self.assertEqual(recs["status/2026-07-01-daily"]["truth_state"], "archived")
        # accepted ADR is current truth
        self.assertEqual(recs["adr/0001-x"]["truth_state"], "current")
        # guide with no frontmatter still gets identity + title from H1
        self.assertEqual(recs["user-guide"]["title"], "User guide")

    def test_sidecar_wins_over_derivation(self):
        cwd = os.getcwd()
        os.chdir(self.dir)
        try:
            ia.write_sidecar("plan/alpha", {"owner": "rick",
                                            "truth_state": "archived"})
            recs = ia.build_records()
            self.assertEqual(recs["plan/alpha"]["owner"], "rick")
            self.assertEqual(recs["plan/alpha"]["truth_state"], "archived")
        finally:
            os.chdir(cwd)

    def test_validate_and_check(self):
        recs = self.records()
        for rec in recs.values():
            self.assertEqual(ia.validate_record(rec), [], rec["wiki_key"])
        bad = {"wiki_key": "x", "doc_type": "nope", "truth_state": "maybe",
               "source": "f.md", "relates_to": [{"type": "eats", "target": "y"}, "junk"]}
        problems = ia.validate_record(bad)
        self.assertTrue(any("bad doc_type" in p for p in problems))
        self.assertTrue(any("bad truth_state" in p for p in problems))
        self.assertTrue(any("unknown edge type" in p for p in problems))
        self.assertTrue(any("malformed" in p for p in problems))

    def test_cli_inventory_write_and_check(self):
        p = run(self.dir, "ia-inventory")
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertIn("docs inventoried", p.stdout)
        inv = json.load(open(os.path.join(self.dir, ia.INVENTORY)))
        self.assertEqual(inv["version"], 1)
        self.assertTrue(all("wiki_key" in d for d in inv["docs"]))
        c = run(self.dir, "ia-inventory", "--check")
        self.assertEqual(c.returncode, 0, c.stdout + c.stderr)
        # stale after a doc change
        self.write("docs/adr/0001-x.md",
                   "---\nid: 1\nslug: x\ntitle: X\ndate: 2026-07-01\n"
                   "status: superseded\nsuperseded_by: 2\n---\n# ADR-0001\n")
        c = run(self.dir, "ia-inventory", "--check")
        self.assertEqual(c.returncode, 1)
        self.assertIn("stale", c.stdout)

    def test_cli_wiki_key(self):
        p = run(self.dir, "wiki-key", "docs/plans/2026-07-01-alpha.md", "-v")
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertEqual(p.stdout.splitlines()[0], "plan/alpha")
        self.assertIn("canonical: plan/2026-07-01-alpha", p.stdout)
        p = run(self.dir, "wiki-key", "README.md")
        self.assertEqual(p.returncode, 1)

    def test_plan_lifecycle_from_fold(self):
        # no items at all = legacy pre-worklog plan; those shipped
        self.assertEqual(ia.plan_lifecycle({"items": []}, {}), "completed")
        # items that aren't in the fold yet = planned
        self.assertEqual(ia.plan_lifecycle({"items": ["ZZ"]}, {}), "planned")
        items = {"A": {"status": "todo"}, "B": {"status": "todo"}}
        self.assertEqual(ia.plan_lifecycle({"items": ["A", "B"]}, items), "planned")
        items["A"]["status"] = "in_progress"
        self.assertEqual(ia.plan_lifecycle({"items": ["A", "B"]}, items), "active")
        items["A"]["status"] = "done"
        items["B"]["status"] = "cancelled"
        self.assertEqual(ia.plan_lifecycle({"items": ["A", "B"]}, items), "completed")


class TestNormalize(TestInventory):
    """Same sandbox; exercises ia-normalize end to end."""

    def test_normalize_backfills_then_noop(self):
        p = run(self.dir, "ia-normalize")
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertIn("normalization(s) applied", p.stdout)
        # frozen plan got a sidecar, artifact untouched
        side = os.path.join(self.dir, "docs/.index/plan/alpha.yml")
        self.assertTrue(os.path.exists(side))
        with open(os.path.join(self.dir, "docs/plans/2026-07-01-alpha.md")) as fh:
            self.assertFalse(fh.read().startswith("---\nwiki_key"))
        # guide got in-place frontmatter, body intact
        with open(os.path.join(self.dir, "docs/user_guide/user-guide.md")) as fh:
            text = fh.read()
        self.assertIn("wiki_key: user-guide", text)
        self.assertIn("# User guide", text)
        # ADR got wiki_key + truth_state without disturbing its schema
        with open(os.path.join(self.dir, "docs/adr/0001-x.md")) as fh:
            self.assertIn("wiki_key: adr/0001-x", fh.read())
        a = run(self.dir, "adr", "check")
        self.assertEqual(a.returncode, 0, a.stdout + a.stderr)
        # ledger gained self-description
        pub = json.load(open(os.path.join(self.dir, ".work/published.json")))
        self.assertEqual(pub["plan/alpha"]["canonical_key"], "plan/2026-07-01-alpha")
        self.assertEqual(pub["plan/alpha"]["truth_state"], "superseded")
        # second run is a no-op; --check agrees
        p2 = run(self.dir, "ia-normalize")
        self.assertIn("no-op", p2.stdout)
        c = run(self.dir, "ia-normalize", "--check")
        self.assertEqual(c.returncode, 0, c.stdout)

    def test_check_reports_without_writing(self):
        c = run(self.dir, "ia-normalize", "--check")
        self.assertEqual(c.returncode, 1)
        self.assertIn("needs: ", c.stdout)
        self.assertFalse(os.path.exists(os.path.join(self.dir, "docs/.index")))

    def test_truth_state_recomputed_not_pinned(self):
        run(self.dir, "ia-normalize")
        side = os.path.join(self.dir, "docs/.index/status/2026-07-02-daily.yml")
        with open(side) as fh:
            self.assertIn("truth_state: current", fh.read())
        # a newer daily lands; the old one must flip to archived on re-run
        self.write("docs/status/2026-07-03-daily.md",
                   "---\nkind: daily\ndate: 2026-07-03\nwindow: {from: c, to: d}\n"
                   "through: 01AAAA\ngenerated_at: 2026-07-03T00:00:00Z\n---\n# S3\n")
        run(self.dir, "ia-normalize")
        with open(side) as fh:
            self.assertIn("truth_state: archived", fh.read())

    def test_authored_sidecar_fields_survive(self):
        run(self.dir, "ia-normalize")
        side = os.path.join(self.dir, "docs/.index/plan/alpha.yml")
        with open(side, "a") as fh:
            fh.write("owner: rick\n")
        run(self.dir, "ia-normalize")
        with open(side) as fh:
            self.assertIn("owner: rick", fh.read())

    def test_snapshot_chain_and_restamped_snapshot(self):
        os.makedirs(os.path.join(self.dir, "docs/roadmap"))
        for stem in ("2026-07-01_v1-release", "2026-07-02_v2-release"):
            self.write("docs/roadmap/%s.md" % stem,
                       "---\nwiki_key: roadmap-snapshot/%s\n"
                       "doc_type: roadmap-snapshot\ntruth_state: snapshot\n"
                       "---\n# Roadmap\n" % stem)
        run(self.dir, "ia-normalize")
        with open(os.path.join(
                self.dir, "docs/.index/roadmap-snapshot/2026-07-02_v2-release.yml")) as fh:
            text = fh.read()
        self.assertIn("supersedes: roadmap-snapshot/2026-07-01_v1-release", text)
        self.assertIn("release: v2", text)


class TestRender(TestInventory):
    """Reader plane: Home, Sidebar, indexes, manifest, aliases."""

    def setUp(self):
        super().setUp()
        self.write("docs/roadmap.md",
                   "---\nwiki_key: roadmap\ndoc_type: roadmap\n"
                   "truth_state: current\nsource_hash: abcd\n"
                   "generated_at: 2026-07-02T00:00:00Z\n---\n\n# Roadmap\n")
        os.makedirs(os.path.join(self.dir, "docs/roadmap"))
        self.write("docs/roadmap/2026-07-01_v1-release.md",
                   "---\nwiki_key: roadmap-snapshot/2026-07-01_v1-release\n"
                   "doc_type: roadmap-snapshot\ntruth_state: snapshot\n"
                   "date: 2026-07-01\nname: v1-release\n---\n# Roadmap\n")
        run(self.dir, "ia-normalize")

    def test_render_pages_manifest_aliases(self):
        p = run(self.dir, "ia-render")
        self.assertEqual(p.returncode, 0, p.stderr)
        home = self.read("docs/.index/rendered/home.md")
        self.assertIn("## What are we working on now?", home)
        self.assertIn("[[Roadmap]]", home)
        self.assertIn("latest status: [[Status-2026-07-02-daily]]", home)
        side = self.read("docs/.index/rendered/_Sidebar.md")
        self.assertIn("### Current truth", side)
        self.assertIn("### History", side)
        rel = self.read("docs/.index/rendered/releases.md")
        self.assertIn("## v1", rel)
        self.assertIn("Roadmap snapshot: [[Roadmap-2026-07-01_v1-release]]", rel)
        dec = self.read("docs/.index/rendered/decisions.md")
        self.assertIn("ADR-0001-x", dec)
        # alpha is superseded: the decisions row says so, with the successor
        self.assertIn("superseded by [[Plan-beta]]", dec)
        man = json.load(open(os.path.join(self.dir, ia.INVENTORY.replace(
            "_inventory.json", "publish-manifest.json"))))
        by_key = {p["wiki_key"]: p for p in man["pages"]}
        self.assertEqual(by_key["home"]["source"],
                         "docs/.index/rendered/home.md")
        alpha = by_key["plan/alpha"]
        self.assertTrue(alpha["frozen"])
        self.assertIn("Superseded", alpha["banner"])
        self.assertIn("render_hash", alpha)
        self.assertIn("sidebar", man)
        aliases = json.load(open(os.path.join(
            self.dir, "docs/.index/aliases.json")))
        self.assertEqual(aliases["plan/alpha"], "plan/2026-07-01-alpha")
        # deterministic + check mode
        c = run(self.dir, "ia-render", "--check")
        self.assertEqual(c.returncode, 0, c.stdout)

    def test_banner_changes_render_hash_not_source(self):
        """The legacy-banner republish loop: a truth flip changes the
        manifest render_hash while the frozen source is untouched."""
        run(self.dir, "ia-render")
        man1 = json.load(open(os.path.join(
            self.dir, "docs/.index/publish-manifest.json")))
        h1 = {p["wiki_key"]: p["render_hash"] for p in man1["pages"]}
        # a newer daily archives the old one -> its banner flips
        self.write("docs/status/2026-07-03-daily.md",
                   "---\nkind: daily\ndate: 2026-07-03\nwindow: {from: c, to: d}\n"
                   "through: 01AAAA\ngenerated_at: 2026-07-03T00:00:00Z\n---\n# S3\n")
        run(self.dir, "ia-normalize")
        run(self.dir, "ia-render")
        man2 = json.load(open(os.path.join(
            self.dir, "docs/.index/publish-manifest.json")))
        h2 = {p["wiki_key"]: p["render_hash"] for p in man2["pages"]}
        key = "status/2026-07-02-daily"
        self.assertNotEqual(h1[key], h2[key])
        self.assertEqual(h1["plan/alpha"], h2["plan/alpha"])  # untouched

    def test_check_flags_stale_render(self):
        run(self.dir, "ia-render")
        self.write("docs/plans/2026-07-04-gamma.md",
                   "---\ndate: 2026-07-04\nslug: gamma\ntitle: Gamma\n"
                   "epic: null\nitems: []\n---\n# Gamma\n")
        c = run(self.dir, "ia-render", "--check")
        self.assertEqual(c.returncode, 1)
        self.assertIn("stale: ", c.stdout)

    def test_ia_index_wrapper_runs_pipeline(self):
        p = run(self.dir, "ia-index")
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertTrue(os.path.exists(os.path.join(self.dir, ia.INVENTORY)))
        self.assertTrue(os.path.exists(os.path.join(
            self.dir, "docs/.index/rendered/_Sidebar.md")))

    def read(self, rel):
        with open(os.path.join(self.dir, rel), encoding="utf-8") as fh:
            return fh.read()


class TestGraph(TestRender):
    """Traceability: graph build, link-pr, trace-check, seeding."""

    def setUp(self):
        super().setUp()
        # two items: one clean chain, one with no links at all
        p = run(self.dir, "add", "Wire the frobnicator", "--level", "task",
                "--kind", "feature", "--milestone", "v1",
                "--plan", "docs/plans/2026-07-01-alpha.md")
        self.iid = p.stdout.strip().splitlines()[-1]
        p = run(self.dir, "add", "Orphan chore", "--level", "task",
                "--kind", "ops")
        self.orphan = p.stdout.strip().splitlines()[-1]

    def test_graph_edges_and_traceability_page(self):
        run(self.dir, "close", self.iid)
        g = run(self.dir, "ia-graph")
        self.assertEqual(g.returncode, 0, g.stderr)
        graph = json.load(open(os.path.join(self.dir, "docs/.index/_graph.json")))
        edges = {(e["from"], e["type"], e["to"]) for e in graph["edges"]}
        self.assertIn(("item/" + self.iid, "targets", "release/v1"), edges)
        self.assertIn(("plan/alpha", "produces", "item/" + self.iid), edges)
        self.assertIn(("plan/2026-07-02-beta", "supersedes", "plan/alpha"), edges)
        self.assertIn(("roadmap-snapshot/2026-07-01_v1-release", "snapshot-of",
                       "roadmap"), edges)
        run(self.dir, "ia-render")
        trace = self.read("docs/.index/rendered/traceability.md")
        self.assertIn("Wire the frobnicator", trace)
        self.assertIn("produced-by: [[Plan-alpha]]", trace)

    def test_link_pr_is_overlay_only(self):
        p = run(self.dir, "link-pr", self.iid, "--pr", "7")
        self.assertEqual(p.returncode, 0, p.stderr)
        side = self.read("docs/.index/item/%s.yml" % self.iid)
        self.assertIn("pr: 7", side)
        # overlay only: no item state in the sidecar
        self.assertNotIn("status", side)
        self.assertNotIn("title", side)
        # idempotent
        run(self.dir, "link-pr", self.iid, "--pr", "7")
        self.assertEqual(self.read("docs/.index/item/%s.yml" % self.iid).count("pr: 7"), 1)
        graph = json.loads(run(self.dir, "ia-graph").stdout and open(
            os.path.join(self.dir, "docs/.index/_graph.json")).read())
        edges = {(e["from"], e["type"], e["to"]) for e in graph["edges"]}
        self.assertIn(("item/" + self.iid, "lands-in", "pr/7"), edges)
        bad = run(self.dir, "link-pr", self.iid)
        self.assertEqual(bad.returncode, 1)

    def test_trace_check_warn_and_strict(self):
        run(self.dir, "close", self.iid)
        run(self.dir, "close", self.orphan)
        w = run(self.dir, "trace-check")
        self.assertEqual(w.returncode, 0)          # warn level never fails
        self.assertIn("no plan link", w.stdout)     # orphan has no plan
        self.assertIn("no external ticket", w.stdout)
        s = run(self.dir, "trace-check", "--strict")
        self.assertEqual(s.returncode, 1)
        self.assertIn("no PR/commit link", s.stdout)
        # open items are not in scope
        self.assertNotIn("frobnicator, todo", s.stdout)

    def test_ticket_body_projection(self):
        run(self.dir, "link-pr", self.iid, "--pr", "9")
        p = run(self.dir, "ticket-body", self.iid)
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertIn("## Summary", p.stdout)
        self.assertIn("Produced by plan: [Alpha](https://x/wiki/Plan-alpha)",
                      p.stdout)
        self.assertIn("Ships in: v1", p.stdout)
        self.assertIn("delivered by: PR #9", p.stdout)
        self.assertIn("worklog `%s`" % self.iid, p.stdout)
        bad = run(self.dir, "ticket-body", "01NOPE")
        self.assertEqual(bad.returncode, 1)

    def test_seed_edges_propose_only_and_deduped(self):
        self.write("docs/plans/2026-07-01-alpha.md",
                   "---\ndate: 2026-07-01\nslug: alpha\ntitle: Alpha\n"
                   "epic: null\nitems: [%s]\n---\n# Alpha\n\n"
                   "This enacts ADR-0001 per spec §5.4.\n" % self.iid)
        p = run(self.dir, "ia-graph", "--seed")
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertIn("plan/alpha -decides-> adr/0001-x", p.stdout)
        self.assertIn("-implements-> spec#5.4", p.stdout)
        sug = self.read(".work/suggestions.jsonl")
        self.assertIn("proposed_edge", sug)
        # nothing was auto-written to sidecars or docs
        self.assertNotIn("relates_to",
                         self.read("docs/.index/plan/alpha.yml"))
        # re-seed is a no-op (dedupe against existing suggestions)
        p2 = run(self.dir, "ia-graph", "--seed")
        self.assertIn("0 edge suggestion(s)", p2.stdout)


if __name__ == "__main__":
    unittest.main(verbosity=1)
