#!/usr/bin/env python3
"""Tests for bin/render_roadmap.py -- WORKLOG-SPEC section 13.1.

The renderer must be byte-deterministic: the pre-commit freshness check
regenerates and diffs, so any nondeterminism (wall-clock timestamps, dict
order) makes every commit fail.
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "bin"))
sys.path.insert(0, os.path.dirname(__file__))
from render_roadmap import render  # noqa: E402
from test_fold import write_log  # noqa: E402


def ev(n, item, op, **kw):
    e = {"ev": f"01J8X{n:04d}A0", "ts": "t", "actor": "t", "item": item, "op": op}
    e.update(kw)
    return e


class TestDeterminism(unittest.TestCase):
    EVENTS = [
        ev(1, "E1", "create", set={"type": "epic", "title": "Auth refactor",
                                   "status": "todo", "priority": "P0"}),
        ev(2, "T1", "create", set={"type": "task", "title": "Extract middleware",
                                   "status": "in_progress", "priority": "P0",
                                   "parent": "E1"}),
        ev(3, "T2", "create", set={"type": "task", "title": "Session migration",
                                   "status": "todo", "priority": "P1",
                                   "parent": "E1", "depends_on": ["T1"]}),
    ]

    def test_identical_output_regardless_of_file_order(self):
        a = render([write_log(self.EVENTS)])
        b = render([write_log(list(reversed(self.EVENTS)))])
        self.assertEqual(a, b)

    def test_two_renders_of_same_log_are_identical(self):
        path = write_log(self.EVENTS)
        self.assertEqual(render([path]), render([path]))

    def test_generated_marker_and_hash_present(self):
        out = render([write_log(self.EVENTS)])
        self.assertIn("<!-- GENERATED by worklog roadmap-render. DO NOT EDIT. -->", out)
        self.assertIn("<!-- source-hash: ", out)
        self.assertIn("<!-- generated-at: ", out)
        self.assertNotIn("generated-at: never", out)


class TestSections(unittest.TestCase):
    def test_in_progress_lands_in_now(self):
        out = render([write_log([
            ev(1, "A", "create", set={"type": "task", "title": "Mid-flight",
                                      "status": "in_progress", "priority": "P2"}),
        ])])
        now = out.split("## Now")[1].split("## Next")[0]
        self.assertIn("Mid-flight", now)

    def test_unblocked_p2_is_next_blocked_p2_is_later(self):
        out = render([write_log([
            ev(1, "D1", "create", set={"type": "task", "title": "Dep",
                                       "status": "todo", "priority": "P2"}),
            ev(2, "B1", "create", set={"type": "task", "title": "Waiting",
                                       "status": "todo", "priority": "P2",
                                       "depends_on": ["D1"]}),
        ])])
        nxt = out.split("## Next")[1].split("## Later")[0]
        later = out.split("## Later")[1]
        self.assertIn("Dep", nxt)
        self.assertIn("Waiting", later)

    def test_blocked_by_column_names_the_open_blocker(self):
        out = render([write_log([
            ev(1, "DEP12345XX", "create", set={"type": "task", "title": "Dep",
                                               "status": "todo", "priority": "P2"}),
            ev(2, "B1", "create", set={"type": "task", "title": "Waiting",
                                       "status": "todo", "priority": "P2",
                                       "depends_on": ["DEP12345XX"]}),
        ])])
        self.assertIn("DEP12345", out.split("## Later")[1])

    def test_closed_items_and_epics_do_not_appear_as_rows(self):
        out = render([write_log([
            ev(1, "E1", "create", set={"type": "epic", "title": "TheEpic",
                                       "status": "todo", "priority": "P1"}),
            ev(2, "T1", "create", set={"type": "task", "title": "Shipped",
                                       "status": "todo", "priority": "P1",
                                       "parent": "E1"}),
            ev(3, "T1", "close", set={"status": "done"}),
            ev(4, "T2", "create", set={"type": "task", "title": "Open task",
                                       "status": "todo", "priority": "P1",
                                       "parent": "E1"}),
        ])])
        self.assertNotIn("| Shipped |", out)          # closed: no table row
        self.assertNotIn("| TheEpic |", out)          # epic: heading, not row
        self.assertIn("### TheEpic", out)


class TestEpicProgress(unittest.TestCase):
    def test_done_counts_cancelled_does_not(self):
        out = render([write_log([
            ev(1, "E1", "create", set={"type": "epic", "title": "Auth",
                                       "status": "todo", "priority": "P1"}),
            ev(2, "T1", "create", set={"type": "task", "title": "One",
                                       "status": "todo", "priority": "P1", "parent": "E1"}),
            ev(3, "T2", "create", set={"type": "task", "title": "Two",
                                       "status": "todo", "priority": "P1", "parent": "E1"}),
            ev(4, "T3", "create", set={"type": "task", "title": "Three",
                                       "status": "todo", "priority": "P1", "parent": "E1"}),
            ev(5, "T2", "close", set={"status": "done"}),
            ev(6, "T3", "close", set={"status": "cancelled"}),
        ])])
        self.assertIn("1 of 2 done", out)


class TestNeedsAttention(unittest.TestCase):
    def test_conflict_is_surfaced_with_resolve_hint(self):
        out = render([write_log([
            ev(1, "A1", "create", set={"type": "task", "title": "Contested",
                                       "status": "todo", "priority": "P1"}),
            ev(2, "A1", "conflict", set={"field": "priority",
                                         "local": "P1", "remote": "P0"}),
        ])])
        self.assertIn("## Needs attention", out)
        self.assertIn("worklog resolve A1 --field priority", out)


if __name__ == "__main__":
    unittest.main()
